### ISSUE TITLE
useForm 验证问题反馈

### ISSUE THREAD

**Issue by yandixuan** [vueComponent/use#12]
## 在form表单 item里 使用  tree-select 设置验证触发 blur:'change' 验证无法通过

![image](https://user-images.githubusercontent.com/23276822/94341158-d5123780-fff6-11ea-9374-ee50f00895e4.png)

```
<a-form v-bind="layout" layout="horizontal">
      <a-form-item v-bind="validateInfos.menuId" label="所属菜单">
        <a-tree-select
          v-model:value="modelRef.menuId"
          :treeData="menuTreeData"
          :replaceFields="{ children: 'children', label: 'menuName', value: 'id', key: 'id' }"
          :dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
          placeholder="请选择所属菜单"
          @change="handleMenuTreeSelectChange"
        ></a-tree-select>
      </a-form-item>
      <a-form-item label="菜单编码">
        <a-input v-model:value="modelRef.menuCode" disabled></a-input>
      </a-form-item>
      <a-form-item v-bind="validateInfos.buttonName" label="按钮名称">
        <a-input v-model:value="modelRef.buttonName" placeholder="请输入按钮名称"></a-input>
      </a-form-item>
      <a-form-item v-bind="validateInfos.buttonKey" label="按钮标识">
        <a-input v-model:value="modelRef.buttonKey" placeholder="请输入按钮标识"></a-input>
      </a-form-item>
    </a-form>

     const rulesRef = reactive({
      menuId: [{ required: true, message: '必填项', trigger: 'change' }],
      buttonKey: [{ required: true, message: '必填项', trigger: 'blur' }],
      buttonName: [{ required: true, message: '必填项', trigger: 'blur' }],
    });
```

## 报错如下
![image](https://user-images.githubusercontent.com/23276822/94341197-11459800-fff7-11ea-89c2-c56eb62bae78.png)

**Comment by tangjinzhou** [comment]
通过这个https://codesandbox.io/s/charming-stonebraker-24ixq    给一个可以复现的示例吧    我本地没能复现

**Comment by yandixuan** [comment]
@tangjinzhou 
https://codesandbox.io/s/sharp-moser-5rvqi?file=/src/App.vue

**Comment by 810505339** [comment]
blur，change  好像没有触发验证！

**Comment by tangjinzhou** [comment]
先添加 type  
```js
menuId: [{ required: true, message: '必填项', trigger: 'change', type: 'number' }],
```

**Comment by 810505339** [comment]
@tangjinzhou antd文档里面好像没有添加type

**Comment by 810505339** [comment]
`export default defineComponent(() => {
    const form = reactive({
        name: ''
    })
    const rules = reactive({
        name: [
            {
                required: true,
                message: '必填项',
                type: 'string',
                trigger: 'blur',

            },
            {
                min: 3,
                max: 5,
                message: 'Length should be 3 to 5',

            }
        ],
    })
    const {resetFields, validate, validateInfos} = useForm(form, rules);
    return () => (<>
        <a-form>
            <a-form-item label="Activity zone"  {...validateInfos.name}>
                <a-input v-model={[form.name, 'value']}/>
            </a-form-item>
        </a-form>
    </>)
})`
@tangjinzhou 
  这样好像不行 触发不了blur

**Comment by 810505339** [comment]
`
export default defineComponent(() => {
    const form = reactive({
        name: ''
    })
    const rules = reactive({
        name: [
            {
                required: true,
                message: '必填项',



            },
            {
                min: 3,
                max: 5,
                message: 'Length should be 3 to 5',
                type: 'string',
                trigger: 'blur',

            }
        ],
    })
    const {resetFields, validate, validateInfos} = useForm(form, rules);
    return () => (<>
        <a-form>
            <a-form-item label='Activity zone' {...validateInfos.name}>
                <a-input v-model={[form.name, 'value']}/>
            </a-form-item>
        </a-form>
    </>)
})

`

@tangjinzhou  这样加上了type好像也触发不了blur

**Comment by 810505339** [comment]
`
export default defineComponent(() => {
    const form = reactive({
        name: ''
    })
    const rules = reactive({
        name: [
            {
                required: true,
                message: '必填项',
            },
            {
                min: 3,
                max: 5,
                message: 'Length should be 3 to 5',
                type: 'string',
                trigger: 'blur',
            }
        ],
    })
    const {resetFields, validate, validateInfos} = useForm(form, rules);
    return () => (<>
        <a-form>
            <a-form-item label='Activity zone' {...validateInfos.name}>
                <a-input v-model={[form.name, 'value']}/>
            </a-form-item>
        </a-form>
    </>)
})
`
@tangjinzhou  加上type好像也触发不了

**Comment by 810505339** [comment]
`
export default defineComponent(() => {
    const form = reactive({
        name: ''
    })
    const rules = reactive({
        name: [
            {
                required: true,
                message: '必填项',
            },
            {
                min: 3,
                max: 5,
                message: 'Length should be 3 to 5',
                type: 'string',
                trigger: 'blur',
            }
        ],
    })
    const {resetFields, validate, validateInfos} = useForm(form, rules);
    return () => (<>
        <a-form>
            <a-form-item label='Activity zone' {...validateInfos.name}>
                <a-input v-model={[form.name, 'value']}/>
            </a-form-item>
        </a-form>
    </>)
})
`
@tangjinzhou  似乎不行

**Comment by 810505339** [comment]
`
export default defineComponent(() => {
    const form = reactive({
        name: ''
    })
    const rules = reactive({
        name: [
            {
                required: true,
                message: '必填项',
            },
            {
                min: 3,
                max: 5,
                message: 'Length should be 3 to 5',
                type: 'string',
                trigger: 'blur',
            }
        ],
    })
    const {resetFields, validate, validateInfos} = useForm(form, rules);
    return () => (<>
        <a-form>
            <a-form-item label='Activity zone' {...validateInfos.name}>
                <a-input v-model={[form.name, 'value']}/>
            </a-form-item>
        </a-form>
    </>)
})`

**Comment by 810505339** [comment]
`
export default defineComponent(() => {
    const form = reactive({
        name: ''
    })
    const rules = reactive({
        name: [
            {
                required: true,
                message: '必填项',
            },
            {
                min: 3,
                max: 5,
                message: 'Length should be 3 to 5',
                type: 'string',
                trigger: 'blur',
            }
        ],
    })
    const {resetFields, validate, validateInfos} = useForm(form, rules);
    return () => (<>
        <a-form>
            <a-form-item label='Activity zone' {...validateInfos.name}>
                <a-input v-model={[form.name, 'value']}/>
            </a-form-item>
        </a-form>
    </>)
})

`

@tangjinzhou  似乎也不行

**Comment by tangjinzhou** [comment]
不同问题分开提问  你的问题我不确定是否相关 @810505339
