### ISSUE TITLE
useForm 疑问

### ISSUE THREAD

**Issue by yandixuan** [vueComponent/use#14]
### 按照网站demo 建立 modelRef ，form-item绑定对应属性时，当清空modelRef初始属性时 表单验证通过。其实表单提交时候modelRef已经变化了，声明modelRef初始属性可以不必须吗？ ：）

**Comment by yandixuan** [comment]
### 我在Modal 弹出表单修改记录 调用 resetFields() API时会触发验证

https://codesandbox.io/s/quizzical-wildflower-h6vm1?file=/src/App.vue 

在调用resetFields() 不应该再打印出validator的验证错误信息了 我是这个意思...

**Comment by tangjinzhou** [comment]
没明白 啥意思

**Comment by yandixuan** [comment]
@tangjinzhou 
![image](https://user-images.githubusercontent.com/23276822/94367466-89cb5800-00ce-11eb-8048-e5a3ed714378.png)


### 注释掉验证通过了

**Comment by Robert-Ro** [comment]
同问，`useForm`里面的`getPropByPath`函数返回对象中的`isValid`的意义，表单新增时，`modelRef`应该是`reactive({})`吧，但如果`modelRef`是`reactive({})`的话，表单可以直接提交，而不会触发检验失败，注释`if (!prop.isValid) continue;`即可触发校验失败的错误提示
