### ISSUE TITLE
import时出错

### ISSUE THREAD

**Issue by disturbwe** [vueComponent/use#6]
![image](https://user-images.githubusercontent.com/36886269/93989043-0226d600-fdbc-11ea-8b23-53126b182b0c.png)

![image](https://user-images.githubusercontent.com/36886269/93988912-db689f80-fdbb-11ea-8940-fb01fd0a1de7.png)

**Comment by disturbwe** [comment]
这是在vite里，作者是不是没有适配vite呀

**Comment by tangjinzhou** [comment]
update to 0.0.1-alpha.5
